services:
  packageclicker:
    image: ghcr.io/larrymotalavigne/packageclicker:latest
    container_name: packageclicker
    restart: unless-stopped
    networks:
      - packageclicker

networks:
  packageclicker:
    name: packageclicker
    driver: bridge
